#!/usr/bin/env python3
import os
import sys

def error():
    os.system("notify-send 'DementedIGPU: notify error. "
        "Run DementedIGPU/notify in terminal to debug.")
    sys.exit(2)

code = os.system("lsmod | grep -w bbswitch") >> 8
if code == 0:
    os.system("notify-send 'DementedIGPU: iGPU used (bbswitch detected).'")
    sys.exit(0)
elif code != 1:
    error()

code = os.system("lsmod | grep nvidia") >> 8
if code == 0:
    os.system("notify-send 'DementedIGPU: Nvidia used (no bbswitch detected).'")
    sys.exit(0)
elif code != 1:
    error()

os.system("notify-send 'DementedIGPU: Unsure... "
    "no bbswitch or nvidia module detected.'")
sys.exit(2)

