#!/usr/bin/env python3
from demented_igpu_lib import process_strict, backup, remark

backup("/etc/default/grub", "grub", True)

process_strict("cp", ".grub", "/etc/default/grub")
remark("/etc/default/grub restored from .grub backup")
